const books=[
  {country:"Algeria",region:"maghreb",reviewed:true,book:"What the Day Owes the Night",author:"Yasmina Khadra",tags:["colonialism","love","pieds-noirs","independence"],summary:"This book is a perfect example of why reading fiction is important. Reading fiction like this forces the reader to internalize and grapple with historical events in a way that a straightforward history never could. In this case, by personalizing something like the Algerian independence struggle, the reader must reevaluate the dry numbers, facts and statistics littering the historical record and connect them to the actual people and struggles behind them.",quotes:["Have you ever dared, Younes, even once in your life?","If a woman loves you, no star is beyond your grasp, no god can touch you.","Only love can make good the misfortunes and evils of the world."],poem:{title:"Kassaman (We Pledge)",author:"Moufdi Zakaria",clip:"We pledge by the lightning that destroys,\nBy the streams of generous blood being shed,\nBy the bright flags that wave,\nO Algeria, live and bear witness—",link:"http://fuuo.blogspot.com/2010/07/poet-of-week-from-algeria-moufdi-zakaria.html"},link:"https://fuuo.blogspot.com/2018/04/love.fiction.algerianwarofindependence.html"},
  {country:"Libya",region:"maghreb",reviewed:true,book:"Confines of the Shadow",author:"Alessandro Spina",tags:["colonialism","Italian Libya","Benghazi","occupation"],summary:"I came across this book through a post on the Arabist's excellent blog. The author of the post—Ursula Lindsey—wrote such a great opening hook: 'Alessandro Spina was a Syrian Maronite who grew up in Ben Ghazi, was educated and wrote in Italian, and over the course of 40 years penned an extraordinary cycle of novels about the bloody establishment, brief flourishing and troubled aftermath of the Italian colony in Libya.' So a novel by a Catholic Syrian that grew up in Libya, was educated in Italy and wrote in Italian, and his work has only recently been translated into English...awesome.",quotes:["To be a foreigner is a magical condition: this land will never belong to me, no matter how many cannons and rifles I bring here.","Generosity cannot overcome our fundamental problem: is our presence here legitimate?","The native is a living shadow."],poem:{title:"East of Carthage: An Idyll",author:"Khaled Mattawa",clip:"I have been away so long\nI no longer know what I miss.\nThe language, the bread,\nthe smell of dust after rain—",link:"http://fuuo.blogspot.com/2010/11/poet-of-week-sad-truth-of-matter.html"},link:"http://fuuo.blogspot.com/2015/11/libya.spina.naffis.sahely.benghazi.italy.faoreadinglist.tripoli.html"},
  {country:"Morocco",region:"maghreb",reviewed:true,book:"Leaving Tangier",author:"Tahar Ben Jelloun",tags:["immigration","Europe","diaspora","corruption","identity"],summary:"Loved it because this was a sad, tragic, beautifully written tale about loneliness, despair, hope and home. The strength of this novel is that it doesn't hold back in its indictment of the Moroccan government's societal failures but also doesn't hold living in Europe as a golden solution to the problems of most Moroccans.",quotes:["Exile revealed the true dimensions of calamity.","You know, from Morocco you can see Spain, but it doesn't work like that in the opposite direction.","We are all called upon to leave our homes...because our country is often not rich enough, or loving enough, or generous enough to keep us at home."],poem:{title:"Elegy for Love",author:"Hassan El Ouazzani",clip:"I write you letters in the language\nof longing, which has no alphabet,\nonly the weight of what remains\nwhen the beloved has gone—",link:"http://fuuo.blogspot.com/2010/04/lawful-magic-why-i-will-have-poem-of.html"},link:"http://kruzoo.blogspot.com/2016/09/leavingtangier.africareadinglist.jelloun.morocco.mo.fao.html"},
  {country:"Tunisia",region:"maghreb",reviewed:true,book:"Lion Mountain",author:"Mustapha Tlili",tags:["independence","modernity","sacred geography","Jasmine Revolution"],summary:"Lion Mountain is a novel of collisions — physical and spiritual, emotional and political, urban and rural, French and Tunisian, dictators and villagers, mother and son. Tlili paints a secluded village modeled on Feriana, the home of his youth — an ancient place lost amidst the desert steppes, sheltered always under the shoulder of Lion Mountain. The diviner of this sacred geography is the equally ancient Horia, a widow and fierce defender who bears all of life's adversity with a stoicism that is seemingly unbreakable. The arrival of the outside world sets the novel on a tragic arc as the forces of modernity smother the spiritual life from Horia and her household. In Horia's refusal to let her sacred geography be ripped apart, we see echoes of the defiance that will become Tunisia's Jasmine Revolution decades later.",quotes:["A geography more than physical or human: sacred...In this mystical topography, landmarks determining the rights of each and every individual were perfectly clear.","Time passes, pain is forgotten, horror is forgotten. Only by remaining silent in the face of horror may we escape it.","You set out in search of wisdom and knowledge; out of sacred duty you have become an exile. Are we not all exiles upon this earth? Is not dust our natural abode?","All because of that extraordinary ability with which the Lord has endowed him: the ability to forget. To forget. To forgive."],poem:null,link:"https://fuuo.blogspot.com/2021/02/tunisiajasmine.lionmountain.html"},
  {country:"Mauritania",region:"maghreb",reviewed:true,book:"The Desert and the Drum",author:"Mbarek Ould Beyrouk",tags:["desert","Sahara","nomad","tradition","colonialism","identity"],summary:"'From the moment they arrived, the strangers stole something essential from us, without us feeling we had the right to protest.' This comment by the young Bedouin narrator Rayhana encapsulates the modern-day struggle that Beyrouk seeks to describe. In Rayhana's case, these strangers were a mixture of fellow countrymen and foreign investors looking for minerals. The theft in question is not one of gold or ore but of proximity and privacy. For Rayhana, the strangers' arrival severs that separation on every level forcing her to leave her tribe, and most importantly, to consider what it means to exist as an individual — a concept completely foreign to most Bedouin. The drum is her tribe's ancient token, guarded and carried for centuries and imbued with mystic power. For Rayhana, however, the drum represents everything taken from her, so she absconds with it setting off a tragic chain of events. Beyrouk is a gifted author and writes beautifully as he observes the stark difference between modern 'civilization' and Bedouin life.",quotes:["From the moment they arrived, the strangers stole something essential from us, without us feeling we had the right to protest.","So what? Do you think I'm ashamed of that? Do you think I'd rather have what you have? Your grimy faces, your vacant eyes, your directionless lives, the prisons you live in, the dead things you use for transport? Do you think you're better than me?","I was clearly from elsewhere; from the lands that were white with sand and black with fury.","Is there anyone more ignorant than someone who can't find their way?"],poem:null,link:"https://fuuo.blogspot.com/2026/06/the-desert-and-drum-by-mbarek-ould.html"},
  {country:"Cameroon",region:"west",reviewed:true,tags:["colonialism","slavery","immigration","America","oil","identity"],
   books:[
     {title:"Houseboy",author:"Ferdinand Oyono",summary:"Oyono crafts a beautiful, tragic and damning tale about being a 'black Frenchman' in colonial Cameroon. The question of identity is at the center of this tale of a houseboy named Toundi with hopes of assimilation. With his near-last dying words being 'What are we blackmen who are called French?' one gets the sense it's not going to end well for the young man.",quotes:["What are we blackmen who are called French?","The dog of the King is the King of dogs."],link:"http://kruzoo.blogspot.com/2016/09/houseboy-loved-it-because-oyono-crafts.html"},
     {title:"Season of the Shadow",author:"Léonora Miano",summary:"What were the beginnings of slavery like for those villagers who were first kidnapped? Miano transports the reader to those early terrifying days and likens the horror of slavery to a shadow of darkness whose advance can't be stopped nor hidden from. A village awakens to its huts ablaze and 12 men vanished — evil unchecked growing from the slimmest of shadows to an all-encompassing darkness.",quotes:["Evil unchecked can quickly grow from the slimmest of shadows to an all-encompassing darkness."],link:"https://fuuo.blogspot.com/2019/07/kruses-keys-read-season-of-shadow-to.html"},
     {title:"Behold the Dreamers / How Beautiful We Were",author:"Imbolo Mbue",summary:"The novel's power comes in Mbue's ability to capture both the strengths and the hollowness of the promise of America. In How Beautiful We Were, Mbue is restrained as she refuses to offer a hopeful note about the plight of this fictional country—instead she offers a cold and despairing eulogy.",quotes:["The problem with America is that it makes you dream.","Someday, when you're old, you'll see the ones who came to kill us and the ones who'll run to save us are the same."],link:"https://www.beyondachebe.com/2021/11/behold-dreamers-by-imbolo-mbue-cameroon.html"}
   ],
   poem:{title:"A Poem of Villeneuve St. Georges",author:"Mbella Sonne Dipoko",clip:"Black is the colour of my love's hair\nAnd her body is warm like the tropics\nShe dances with a blue flame\nAnd laughs without shame—",link:"http://fuuo.blogspot.com/2017/04/poet-of-week-from-cameroon-mbella-sonne.html"}},
  {country:"Ghana",region:"west",reviewed:true,tags:["slave trade","diaspora","addiction","family","identity","immigration","science vs faith"],
   books:[
     {title:"Ghana Must Go",author:"Taiye Selasi",summary:"Read It Because this is not a novel about Africa, or Ghana, or Nigeria or immigrants only — this is one of the classic novels about family, identity, loss, and forgiveness that follows you around in your idle thoughts long after you are finished. Selasi's mastery is most evident as she captures the sights, sounds and people of Ghana and Nigeria.",quotes:["The boy was possessed of that brand of indomitable cheerfulness only seen in children living in poverty near the equator: an instinct to laugh at the world as they found it, to find things to laugh at, to know where to look."],link:"http://kruzoo.blogspot.com/2016/03/ghana-must-go-read-it-because-this-is.html"},
     {title:"Homegoing",author:"Yaa Gyasi",summary:"As I listened to Yaa Gyasi's 'Homegoing' I began to see the very clear narrative line that she was drawing between black lives today and an origin story across the Atlantic that began centuries ago. This masterpiece of historical fiction follows the lives of two separated half-sisters and their six generations of descendants beginning in the mid-1700s in West Africa.",quotes:["We believe the one who has power. He is the one who gets to write the story."],link:"http://fuuo.blogspot.com/2019/03/kruseskeys.homegoing.oprah.gyasi.ghana.html"},
     {title:"Transcendent Kingdom",author:"Yaa Gyasi",summary:"The author chooses to focus on the life of one brilliant young scientist and her life as a daughter of Ghanaian immigrants who struggles with her identity as a black woman — science and faith pulling in opposite directions.",quotes:["Am looking for new names for old feelings. My soul is still my soul, even if I rarely call it that."],link:"http://fuuo.blogspot.com/2019/03/kruseskeys.homegoing.oprah.gyasi.ghana.html"}
   ],
   poem:{title:"Kperterkple Serenade (III)",author:"Atukwei Okai",clip:"america\nyou are a funny girl…\neverybody dreams of kissing you",link:"http://fuuo.blogspot.com/2010/10/poet-of-week-from-ghana-atukwei-okai.html"}},
  {country:"Nigeria",region:"west",reviewed:true,tags:["419 fraud","colonialism","identity","Igbo","diaspora"],
   books:[
     {title:"I Do Not Come to You by Chance",author:"Adaobi Tricia Nwaubani",summary:"Read It Because you'll finally get to know that Nigerian Prince who has been emailing you! With an eye for humor and for heart, Nwaubani crafts a classic tragedy that follows the rise of Kingsley as he ascends a 419 crime syndicate. The single aspect that best demonstrates the author's deft writing hands is her ability to humanize Kingsley as he becomes more and more adept at swindling gullible mugus.",quotes:["The glass cup dropped from my hand and colonized a large portion of the marble floor.","No matter what the media proclaimed, we were not villains, and the good people of Eastern Nigeria knew it."],link:"http://kruzoo.blogspot.com/2016/01/419.ng.advancefee.nigerianprince.nwaubani.donotcometoyoubychance.html"},
     {title:"Arrow of God",author:"Chinua Achebe",summary:"Achebe's deepest excavation of colonial disruption to traditional Igbo authority — the story of Ezeulu, chief priest of Ulu, whose resistance to British colonial power leads to catastrophic consequences for his people and his god.",quotes:["We believe the one who has power. He is the one who gets to write the story. So when you study history, you must ask yourself, Whose story am I missing?"],link:"http://kruzoo.blogspot.com/2016/01/419.ng.advancefee.nigerianprince.nwaubani.donotcometoyoubychance.html"},
     {title:"Americanah",author:"Chimamanda Ngozi Adichie",summary:"Adichie's sweeping novel of race, identity, and return maps the experience of a Nigerian woman navigating race in America and Britain before coming home to Lagos.",quotes:[],link:"http://kruzoo.blogspot.com/2016/01/419.ng.advancefee.nigerianprince.nwaubani.donotcometoyoubychance.html"}
   ],
   poem:{title:"In the Small Hours",author:"Wole Soyinka",clip:"In the small hours of the night\nI hear the dead moving,\ntheir footfalls soft as conscience\non the corridors of sleep—",link:"http://fuuo.blogspot.com/2010/06/potw-in-small-hours-by-wole-soyinka.html"}},
  {country:"Senegal",region:"west",reviewed:true,book:"So Long a Letter",author:"Mariama Bâ",tags:["women","polygamy","friendship","epistolary","feminism"],summary:"Read It Because you get to peer into the birth of feminism for a Muslim woman in post-independence Senegal. Bâ won me over with her tender, thoughtful introspective look at the life of a cuckolded, then sister-wifed, then widowed, then independent and finally (maybe) free woman. I found myself rereading paragraphs as she bestowed poetry upon the mundane-seeming tasks of a housewife.",quotes:["The domestic work they carry out, and which is not paid for in hard cash, is essential to the home.","The mirasse commanded by the Koran requires that a dead person be stripped of his most intimate secrets; thus is exposed to others what was carefully concealed."],poem:{title:"Black Woman",author:"Léopold Sédar Senghor",clip:"Naked woman, black woman\nClothed with your colour which is life,\nwith your form which is beauty!\nI grew up in your shadow—",link:"http://fuuo.blogspot.com/2010/07/potw-black-woman-by-senghor.html"},link:"http://kruzoo.blogspot.com/2016/08/senegal.mariamaba.solongaletter.dakar.readinglist.html"},
  {country:"Togo",region:"west",reviewed:true,book:"An African in Greenland",author:"Tété-Michel Kpomassie",tags:["adventure","Greenland","Inuit","travel","identity"],summary:"Loved it because it was unlike anything I've ever read. This is the fantastical post-independence autobiographical tale of a young Togolese boy that leaves his 25 siblings on a whim and starts a 12-year journey from his native country to the chilly northern reaches of Greenland. It all started after he saw a book on Greenland in a missionary bookstore in his village.",quotes:[],poem:null,link:"http://kruzoo.blogspot.com/2016/11/kpomassie.readinglist.an-african-in-greenland-loved-it.html"},
  {country:"Côte d'Ivoire",region:"west",reviewed:true,book:"Allah is Not Obliged",author:"Ahmadou Kourouma",tags:["child soldiers","civil war","West Africa"],summary:"This novel could just as easily have been filed under Sierra Leone or Liberia but I stuck it here since the author is Ivorian. And if we want to get all philosophical about things, most of these books could be filed under multiple countries since the borders are really an artificial colonial construct.",quotes:[],poem:null,link:"http://kruzoo.blogspot.com/2016/11/allahisnotobliged.kourouma.faoreadinglist.html"},
  {country:"Burkina Faso",region:"west",reviewed:true,book:"American Spy",author:"Lauren Wilkinson",tags:["Cold War","espionage","Thomas Sankara","CIA"],summary:"'American Spy' is both a fictionalized telling of Sankara's downfall and a commentary on what it means to be a black woman in both an American and African society. The novel is strongest examining Marie's struggles with Sankara's charisma and his communist views. There are no good answers—only messy and sometimes violent ones.",quotes:["The problem with the good he was doing was that it made his Communism palatable. He was too charismatic."],poem:null,link:"http://fuuo.blogspot.com/2020/08/americanspy.nousvaincrons.wilkinson..html"},
  {country:"Liberia",region:"west",reviewed:true,book:"She Would Be King",author:"Wayetu Moore",tags:["founding","magical realism","American Colonization Society","slavery"],summary:"In Philip Hitti's History of the Arabs, he highlights the long-standing Arab appreciation for oral story-telling and poetry which they call sihr halal — 'lawful magic.' In her debut novel Wayetu Moore channels this idea of lawful magic in her telling of an alternative origin story of the Pepper Coast lands that would become Liberia.",quotes:[],poem:null,link:"https://fuuo.blogspot.com/2020/04/marcusgarvey.wayetumoore.readingthecontinent.kruse.html"},
  {country:"Sierra Leone",region:"west",reviewed:true,book:"The Memory of Love",author:"Aminatta Forna",tags:["civil war","trauma","PTSD","love","endurance"],summary:"With beautiful, striking prose author Aminatta Forna reveals the soul of a nation where nearly everyone is stricken with post-traumatic stress disorder. And while PTSD may be the official western diagnosis, as one local notes: 'You call it a disorder, my friend. We call it life.'",quotes:["People are wrong when they talk of love at first sight. As she walks away from you, what you feel is loss. A premonition of loss.","People think war is the worst this country has ever seen: they have no idea what peace is like. The courage it takes simply to endure."],poem:null,link:"https://fuuo.blogspot.com/2018/06/kruses-key.memoryofcivilwar.love.forna.sierraleone.html"},
  {country:"Cabo Verde",region:"west",reviewed:true,book:"The Last Will and Testament of Senhor da Silva Araújo",author:"Germano Almeida",tags:["Lusophone","love","colonial legacy","melancholy"],summary:"Read It Because this translated piece of Cape Verdean fiction is beautiful, sad, and meandering as it examines the life of a poor peasant boy made good as a successful business owner. The reader is left to wonder: was Adelia actually real or was she a mad creation by a man unable to find his place in Cape Verdean society?",quotes:[],poem:null,link:"http://kruzoo.blogspot.com/2017/01/lastwillandtestament.araujo.capeverde.cv.html"},
  {country:"Mali",region:"west",reviewed:true,pendingReview:true,book:"Bound to Violence",author:"Yambo Ouologuem",tags:["Mali empire","slave trade","colonialism","violence","Prix Renaudot"],summary:"Review pending.",quotes:[],poem:null,link:""},
  {country:"Tanzania",region:"east",reviewed:true,book:"Afterlives / The Gunny Sack",author:"Abdulrazak Gurnah / M.G. Vassanji",tags:["colonialism","WWI","askari","Indian diaspora","Nobel Prize"],summary:"Gurnah's 10th novel spans the timeline from early 1900s east Africa to Tanzanian independence in the early 60s. In it he tells the multi-generational story of several families struggling in an East Africa caught in the middle of a fight between a waning Germany and a desperate teetering British empire. This is the mark of a great book for me—it shifts the attention of the western reader from a default focus on similar western powers and brings it to the personal level of the men and women who own the country and land.",quotes:["The askari left the land devastated, its people starving and dying in the hundreds of thousands, while they struggled on in their blind and murderous embrace of a cause whose origins they did not know."],poem:null,link:"https://www.beyondachebe.com/2023/03/afterlives-tanzania-kindle.html"},
  {country:"Kenya",region:"east",reviewed:true,book:"The Zanzibar Chest",author:"Aidan Hartley",tags:["journalism","memoir","Somalia","East Africa","war correspondent"],summary:"From time to time, God causes men to be born who have a lust to go abroad at the risk of their lives and discover news. If there were ever an engraving to be mounted on the wall of my hypothetical office it would be Kipling's opening quote from this book. One of my favorite books ever — not technically fiction but it sure reads like it.",quotes:[],poem:null,link:"http://fuuo.blogspot.com/2012/11/thezanzibarchest.aidenhartley.summary.review.notes.html"},
  {country:"Uganda",region:"east",reviewed:true,book:"All Our Names",author:"Dinaw Mengestu",tags:["revolution","post-independence","Uganda","Midwest America","love"],summary:"Read It Because it will Break Your Heart. And it's the Great African Novel. As I read through the final pages of the novel and watched the final paragraphs fade away my heart began to ache and break because I didn't want to let the characters go. And then I focused and slowly read through the final line. I won't ruin it for you but that line—oh that line—it will break your heart.",quotes:["No one needs to learn how to kill, but it took the foreigners who came to Africa to show us that it meant nothing to do so."],poem:null,link:"http://kruzoo.blogspot.com/2016/03/allournames.thegreatafricannovel.mengestu.ugandaindependence.fao.html"},
  {country:"Comoros",region:"east",reviewed:true,book:"The Kafir of Karthala",author:"Mohamed Toihiri",tags:["Islam","colonialism","satire","archipelago","coup"],summary:"Published in 2000 amidst one of Comoros' many coups, Toihiri has penned a wry, surprisingly racy novel that satirizes much of the politics and culture of his home country. I was only able to read it because I asked for a copy from the professor who had translated it at the University of Vermont. He was kind enough to send me a Word document with his translation.",quotes:[],poem:null,link:"http://kruzoo.blogspot.com/2016/04/kafirdekhartala.kafirofkhartala.comoros.moroni.auberi.legrandmarriage.fao.html"},
  {country:"Sudan",region:"horn",reviewed:true,book:"The Dissent Channel",author:"Elizabeth Shackleford",tags:["civil war","South Sudan","diplomacy","memoir"],summary:"During a Famous Rivers Africa Group session, we discussed this memoir with the author Lizzy Shackleton. The book covers her experience as a State Department officer in South Sudan and the dissent channel she used to formally object to U.S. policy there.",quotes:[],poem:{title:"A Scream",author:"Muhammed Al-Faituri",clip:"I am the African,\nI am the one who has no father,\nnor mother,\nnor homeland—",link:"https://fuuo.blogspot.com/2012/05/african-poets-of-week-compilation.html"},link:"https://kruzoo.blogspot.com/2021/01/2021-reading-list.html"},
  {country:"Ethiopia",region:"horn",reviewed:true,tags:["Haile Selassie","Derg","revolution","Italian invasion","immigrant experience","homelessness"],
   books:[
     {title:"The Beautiful Things That Heaven Bears",author:"Dinaw Mengestu",summary:"Before Adichie was regaling the world with her story of a relatively privileged immigrant experience in Americanah, Ethiopian author Dinaw Mengestu was pulling back the curtain on a much bleaker immigrant experience. The title comes from the closing lines of Dante's Inferno. Sepha and his friends have escaped the violence in their own country and arrived in America, seeing the stars. Only they soon discover that while their new life may not be hell, it will likely be more like purgatory than paradiso.",quotes:["As it was, I did not come to America to find a better life. I came here running and screaming with the ghosts of an old one firmly attached to my back.","All the best dictators are colonels."],link:"https://fuuo.blogspot.com/2018/05/kruses-keys.mengestu.beautifulthings.selassie.ethiopia.vw.html"},
     {title:"Beneath the Lion's Gaze",author:"Maaza Mengiste",summary:"One of the only African nations to never have been colonized, one of its darkest periods came during the 13-year socialist-Leninist-Marxist rule of the Derg. This military junta overthrew an increasingly oblivious Haile Selassie and set about consolidating power under despot Mengistu Mariam. The novel retells this period through the eyes of one Ethiopian family.",quotes:["The nature of love is to kill for it, or to die."],link:"https://fuuo.blogspot.com/2019/03/krusekeys.fuuo.beneaththelionsgaze.mengiste.ethiopia.html"},
     {title:"The Shadow King",author:"Maaza Mengiste",summary:"Following Mussolini's invasion to avenge Italy's 19th-century embarrassment at the Battle of Adua, Kidane assembles a local militia at exiled Emperor Haile Selassie's behest. His wife Aster leads the women who trail the fighters supplying food and bullets, and eventually convinces him to let her women fight. Mengiste brings to light a forgotten piece of Ethiopia's resistance against Italy.",quotes:["They have come to rewrite history, to alter memory, to resurrect their dead and refashion them as heroes.","She is one woman. She is many women. She is all the sound that exists in the world.","We were the Shadow King."],link:"https://fuuo.blogspot.com/2019/12/kruses-keys-read-shadow-king-to.html"},
     {title:"Prevail",author:"Jeff Pearce",summary:"I can't imagine there's a more well-researched book out there on Ethiopia's decades-long resistance and eventual defeat of an overeager, overconfident, overreaching wannabe colonial power. Canadian author Jeff Pearce's work is strongest as he brings to life the myriad actors, antagonists, and heroes of the saga.",quotes:[],link:"https://fuuo.blogspot.com/2019/04/kruseskey.browncondor.ethiopiahistory.pearce.html"},
     {title:"Mister Drainpipe",author:"Marc Secchia",summary:"Will Drainpipe rediscover and recapture his dignity and past identity? This question is answered against the backdrop of Ethiopia's history over the past 75 years.",quotes:["But now and again there might be a treasure. A smile. A kind greeting; not the automatic or guilty sort, but a genuine word.","It is strange how easily one forgets miracles."],link:"https://fuuo.blogspot.com/2019/"},
     {title:"Someone Like Us",author:"Dinaw Mengestu",summary:"I discovered novelist Dinaw Mengestu several years ago through his beautiful 2007 debut novel The Beautiful Things That Heaven Bears. He later followed it up with his sweeping show-stopper All Our Names, which I called The Great African Novel. While Someone Like Us is far less sweeping than his previous novels, it still builds out Mengestu's tapestry of the immigrant experience in America by focusing on an Ethiopian father and son's evolving relationship. Told against scenes shifting from Ethiopia to France to Chicago and times past and present, Mengestu doesn't shy away from difficult topics like mental health and substance abuse and the toll they take on memory and relationships. In an era where terms like 'immigration' carry a charged weight, Someone Like Us adds important context and hopefully develops increased empathy in the reader on the myriad struggles faced by immigrants by everything from police stops to just not knowing how America works.",quotes:[],link:"https://kruzoo.blogspot.com/2025/11/kruses-keys-read-someone-like-us-to.html"}
   ],
   poem:null},
  {country:"Somalia",region:"horn",reviewed:true,book:"Warriors / The Insanity of God",author:"Gerald Hanley / Nik Ripken",tags:["nomad","clan","faith","persecution","Mogadishu"],summary:"When many critics of Christianity think of missionaries they picture black-clad old-fashioned looking men proselytizing loudly in the streets. If you fall into that category I challenge you to read this book—it will upend your perspective. At one point Ripken's NGO was the ONLY ONE operating in Somalia—his team of 8 was feeding 50,000 refugees a day.",quotes:["In those years in Somalia, we had 150 followers of Jesus in the country. When we left, only four were left alive.","The reason for persecution, then, is that people keep finding Jesus—and, then, they refuse to keep Him to themselves."],poem:{title:"Somalia",author:"K'Naan",clip:"In the place where I come from\nnobody laughs,\neverybody's working so hard\njust to eat—",link:"https://fuuo.blogspot.com/2011/02/poet-of-week-from-somalia-abdirashid.html"},link:"https://fuuo.blogspot.com/2020/04/ArethereSomaliChristians.mogadishu.ripken.html"},
  {country:"Eritrea",region:"horn",reviewed:true,book:"Gratitude in Low Voices",author:"Dawit Gebremichael Habte",tags:["refugee","independence","Italy","Ethiopia","EPLF"],summary:"Equal parts memoir, history and adventure novel, Dawit Habte's book is the story of not only his country's 91-year struggle for independence but also his own incredible journey from a countryside village in Eritrea to the offices of Bloomberg as a software engineer. One thing that struck me was Habte's commentary on the dehumanizing nature of seeking asylum—where you are assumed to be starting anew on a better life despite having a family, people, and country that you call home half a world away.",quotes:["Dry the sea to kill the fish — unofficial motto of Ethiopia as they sought to destroy any hope of Eritrean independence.","A refugee is always a pawn to be used.","Nostalgia is the suffering caused by an unappeased yearning to return."],poem:null,link:"https://fuuo.blogspot.com/2019/09/kruseskeys.bloomberg.habte.read-gratitude-in-low-voices-to.html"},
  {country:"Djibouti",region:"horn",reviewed:true,book:"Transit",author:"Abdourahman Waberi",tags:["refugees","migration","displacement","democracy"],summary:"There's not exactly a ton of Djibouti fiction out there, especially en anglais. But when it comes to Djibouti fiction, the author Waberi reigns supreme. Transit interweaves Bashir's story with that of Harbi as the narrative arc builds toward their intersection. The staying power comes from Waberi's deft touch as he tackles the complexity of his country's history through alternating monologues.",quotes:["Democracy, that hot air of politicians who take bread from whoever giving it.","I'm the product of love without borders; I'm a hyphen between two worlds."],poem:null,link:"https://kruzoo.blogspot.com/2017/11/kruses-key-read-transit-to-understand.html"},
  {country:"Congo (DRC)",region:"central",reviewed:true,book:"A Bend in the River / Dancing in the Glory of Monsters",author:"V.S. Naipaul / Jason Stearns",tags:["Mobutu","Congo Wars","colonialism","Lumumba","Kabila"],summary:"In Dancing in the Glory of Monsters, Stearns attempts to unravel the most complicated conflict that the world never cared about: the two wars in the Congo—as he notes, 'generally we do not care about a strange war fought by black people somewhere in the middle of Africa.' As Stearns digs deeper and deeper into the wars, you are quickly struck by the overwhelming intensity of violence.",quotes:["Africa has the shape of a pistol and Congo is its trigger. —Frantz Fanon","Who has not been Mobutists in this country? We saw you all, dancing in the glory of the monster.","Lies come up in the elevator, the truth takes the stairs but gets here eventually."],poem:{title:"Impuissance",author:"Jean-Baptiste Tati Loutard",clip:"Le fleuve coule encore\ndans les veines de la terre,\nmais nos mains ne peuvent plus\nle tenir—",link:"http://fuuo.blogspot.com/2010/09/poet-of-week-from-congo-jean-baptiste.html"},link:"https://fuuo.blogspot.com/2018/07/kruseskey.mobuto.kabila.lumumba.stearns.dancingcongo.html"},
  {country:"Congo (Republic)",region:"central",reviewed:true,book:"Memoirs of a Porcupine",author:"Alain Mabanckou",tags:["sorcery","fable","oral tradition","superstition"],summary:"This is a difficult novel from renowned author Alain Mabanckou. Mabanckou has penned a pointed tale aimed at taking down the role of backwoods superstition amidst modernity. I will admit I didn't really understand the point of this novel and had to do some research. If you are only going to read one novel from the Republic of Congo, do NOT make it this one.",quotes:[],poem:null,link:"https://fuuo.blogspot.com/2018/04/mabanckou.congo.porcupine.peta.html"},
  {country:"Burundi",region:"central",reviewed:true,book:"Small Country",author:"Gaël Faye",tags:["genocide","Rwanda","childhood","ethnic violence","exile"],summary:"One of the best books that I read this year. I sped through it in three heady days, finishing the last third of the book in a marathon nighttime session tucked in bed next to my sleeping wife. I couldn't put the book down. 'Small Country' is one of the first novels about the Rwandan genocide and was translated into English in 2018 after winning the 2016 Prix Goncourt des Lycéens.",quotes:["I used to think I was exiled from my country. But, in retracing the steps of my past, I have understood that I was exiled from my childhood. Which seems so much crueler.","We were living on the axis of the Great Rift, at the precise spot where Africa fractures. The people of this region mirrored the land.","Poetry may not be news. But it is all that human beings retain from their journey on this earth."],poem:null,link:"https://fuuo.blogspot.com/2019/09/read-small-country-to-see-ethnic.html"},
  {country:"Rwanda",region:"central",reviewed:true,book:"Everything is Yours, Everything is Not Yours",author:"Clemantine Wamariya",tags:["genocide","memoir","refugee","Yale","survivor"],summary:"Powerful autobiographical longread about a Rwandan genocide flee-er turned wandering refugee turned Yale student turned young woman who found her voice. Her story casts aside any easy categorizations of her struggle and journey. I found myself checking the scroll bar on my iPad to see how much of the article I had left—I didn't want it to end.",quotes:[],poem:null,link:"http://fuuo.blogspot.com/2015/07/WIRL.vavasseur.hsc6.rwanda.genocide.rsvp.salter.mg.html"},
  {country:"Equatorial Guinea",region:"central",reviewed:true,book:"By Night the Mountain Burns",author:"Juan Tomás Ávila Laurel",tags:["island","oral tradition","Spanish Africa","memory","colonialism"],summary:"Equatorial Guinea is the only Spanish-speaking country in Africa—it's also the richest African country you've never heard of per capita, due to the discovery of oil there in the 90s. To my knowledge this is still the only work of fiction available in English from Equatorial Guinea.",quotes:[],poem:null,link:"https://fuuo.blogspot.com/2020/06/kruses-keys-read-by-night-mountains.html"},
  {country:"South Africa",region:"southern",reviewed:true,tags:["Apartheid","Booker Prize","Afrikaner","ANC","post-apartheid","memoir","Mandela","Robben Island"],
   books:[
     {title:"The Promise",author:"Damon Galgut",summary:"Of course one isn't awarded the Booker prize for penning a surface-level story about a white family in South Africa. Rather Galgut has written a soaring multi-decade exposition on the promise of a post-Apartheid South Africa writ large. It's a story that encompasses South Africa's promises to its black and coloured people, the ANC's promises to its constituency, as well as the psychic overstep of whites deigning to keep promises that never should have been had to be made in the first place.",quotes:["It is nothing. Your leftovers. That's what you're giving my mother, thirty years too late. It's not yours to give. It already belongs to us."],link:"https://www.beyondachebe.com/2022/01/thepromise.damongalgut.southafrica.booker.html"},
     {title:"Born a Crime",author:"Trevor Noah",summary:"You may know Trevor Noah as the host of the Daily Show but long before he entered the mainstream he was a derelict kid born to a black Xhosa mother and a white Swiss father—one who appeared 'colored' to those around him but who was raised in the Xhosa culture.",quotes:[],link:"https://kruzoo.blogspot.com/2021/01/2021-reading-list.html"},
     {title:"Long Walk to Freedom",author:"Nelson Mandela",summary:"I started Mandela's autobiography a few weeks before his passing after watching it gather digital dust on my kindle bookshelf for over a year. My reticence to dive into this book stemmed from a general disdain for dense, bloated, self-important celebrations of one's life often captured in autobiographies. My misgivings could not have been more misplaced. More a series of chronological vignettes than a traditional biography, Madiba beautiful and humbly tells not only his story — but that of South Africa.",quotes:["Ndiwelimilambo enamagama (I have crossed famous rivers).","For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.","A nation should not be judged by how it treats its highest citizens, but its lowest ones — and South Africa treated its imprisoned African citizens like animals.","I am fundamentally an optimist... part of being optimistic is keeping one's head pointed toward the sun, one's feet moving forward."],link:"https://kruzoo.blogspot.com/2015/02/long-walk-to-freedom-kindle-notes.nelson.mandela.za.html"}
   ],
   poem:{title:"I Want You To Know—A Poem On the Passing of Madiba",author:"Jack Kruse",clip:"I want you to know sweet daughters\nThat a man lived, loved, sacrificed and forgave for his people.\nI want you to know these words\nNdiwelimilambo enamagama—",link:"https://kruzoo.blogspot.com/2013/12/Nelsonmandela.madiba.deathandizindisaquala.poem.daughters.fao.html"}},
  {country:"Zimbabwe",region:"southern",reviewed:true,book:"We Need New Names / They Are Coming",author:"NoViolet Bulawayo / Christopher Mlalazi",tags:["Mugabe","emigration","children","poverty","street kids"],summary:"There's a two-lane road that snakes down the hill from Ivandry in Tana. Here you come to recognize the faces of impoverished kids as they travel in packs, endlessly rapping on your windows as you sit in traffic. Reading NoViolet Bulawayo's 'We Need New Names' brought all of this viscerally back.",quotes:[],poem:null,link:"http://kruzoo.blogspot.com/2015/06/streetkids.mg.weneednewnames.zimbabwe.mugabe.tana.poverty.html"},
  {country:"Mozambique",region:"southern",reviewed:true,book:"Sleepwalking Land",author:"Mia Couto",tags:["civil war","magical realism","oral tradition","Portuguese"],summary:"Mia Couto has crafted a surreal, engrossing tragic tale of the hopelessness of life during the fifteen-year civil war that consumed post-independence Mozambique. Couto focuses on pulling the reader into the psyche of those affected most by war—the ones not doing the killing—the women and the children.",quotes:["The best things in life are those that don't lie ahead."],poem:{title:"If You Want to Know Me",author:"Noémia de Sousa",clip:"If you want to know who I am,\nexamine with careful eyes\nthis piece of black wood\nthat some unknown Makonde brother\ncut and carved\nwith inspired hands—",link:"https://fuuo.blogspot.com/2012/05/african-poets-of-week-compilation.html"},link:"http://kruzoo.blogspot.com/2017/02/sleepwalking-land.miacouto.mozambique.portugal.africa.html"},
  {country:"Zambia",region:"southern",reviewed:true,book:"Cocktail Hour Under the Tree of Forgetfulness",author:"Alexandra Fuller",tags:["memoir","independence","colonial Africa"],summary:"Emily said she appreciated the story's honesty and eye-opening look at both the beauty and sorrow of life. The author shares a unique perspective of a white girl living in Africa during the period of political independence.",quotes:[],poem:{title:"In the Fist of Your Hand",author:"Gwendoline Konie",clip:"You hold the seed of nations\nin the fist of your hand,\nplant it gently, water it\nwith the tears of the living—",link:"http://fuuo.blogspot.com/2011/02/poet-of-week-gwendoline-konie-from.html"},link:"https://kruzoo.blogspot.com/2021/01/2021-reading-list.html"},
  {country:"Malawi",region:"southern",reviewed:true,book:"The Jive Talker",author:"Samson Kambalu",tags:["coming of age","Banda era","Britain","humor"],summary:"Loved It Because Kambalu is a gifted and funny writer who presents his life (and that of his father—the Jive Talker) as an open book. Technically, this isn't fiction but this Malawian Banda-era coming-of-age tale sure reads like it. The book is at its best when the author is in the jive talking zone—whether that be on former President Banda, American Rock n Roll, or bush wisdom regarding safari animals.",quotes:[],poem:{title:"A Love Poem for my Country",author:"Frank Chipasula",clip:"I love you, my country,\nnot the way I love a woman,\nbut the way a son loves a difficult mother\nwho nurses him with bitter milk—",link:"http://fuuo.blogspot.com/2011/01/poet-of-week-frank-chipasula-of-malawi.html"},link:"http://kruzoo.blogspot.com/2016/07/the-jive-talker-or-how-to-get-british.html"},
  {country:"Madagascar",region:"southern",reviewed:true,book:"Beyond the Rice Fields",author:"Naivo",tags:["first novel","colonialism","slavery","Merina","Christianity"],summary:"It's hard to express how much I looked forward to reading this book. I spent three years living and working in Madagascar beginning in late 2013. Prior to my arrival, I had scoured the libraries and internet for anything I could find in English on Madagascar. Then near the end of 2015 I came across a translator who had received a PEN grant to translate it — and it did not disappoint.",quotes:[],poem:{title:"9",author:"Jean-Joseph Rabearivelo",clip:"She who is dead\nbut dances still\nin the dark of memory—\nthe moon turns her face away—",link:"http://fuuo.blogspot.com/2010/08/poem-of-week-jean-joseph-rabearivelo-9.html"},link:"http://kruzoo.blogspot.com/2018/01/read-beyond-rice-fields-to.html"},

  {country:"Egypt",region:"maghreb",reviewed:false,book:"The Cairo Trilogy",author:"Naguib Mahfouz",tags:["Cairo","colonialism","family saga","Nobel Prize","modernity"],summary:"Magnificent story about colonial Egypt and family — read before the project started so no formal review.",quotes:[],poem:null,link:""},

  // ── FUTURE READS ──
  // Maghreb

  // West Africa
  {country:"Angola",region:"west",reviewed:false,book:"Luuanda / Transparent City",author:"Tania Macedo / Ondjaki",tags:["Lusophone","civil war","Luanda"],summary:"",quotes:[],poem:null,link:""},
  {country:"Benin",region:"west",reviewed:false,book:"The Viceroy of Ouidah",author:"Bruce Chatwin",tags:["slave trade","Dahomey"],summary:"",quotes:[],poem:null,link:""},
  {country:"Gambia",region:"west",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"Guinea",region:"west",reviewed:false,book:"My Heart Will Cross This Ocean",author:"Kadiatou Diallo",tags:["family","diaspora","tragedy"],summary:"",quotes:[],poem:null,link:""},
  {country:"Guinea-Bissau",region:"west",reviewed:false,book:"The Ultimate Tragedy",author:"Abdulai Sila",tags:["colonialism","Portuguese Africa"],summary:"",quotes:[],poem:null,link:""},
  {country:"Niger",region:"west",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"São Tomé and Príncipe",region:"west",reviewed:false,book:"Equator",author:"Miguel Sousa Tavares",tags:["Lusophone","island","colonialism","cocoa plantations","slavery"],summary:"",quotes:[],poem:{title:"Plantation",author:"Conceição Lima",clip:"The dead ask:\nWhy do roots sprout from our feet?\n…\nWhat was this kingdom\nthat we planted?",link:"https://talking-about-books.com/2025/04/05/no-gods-live-here-conceicao-lima/"},link:""},

  // East Africa
  {country:"Seychelles",region:"east",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"Mauritius",region:"east",reviewed:false,book:"The Restraint of Beasts",author:"Magnus Mills",tags:["island","Indian Ocean","diaspora"],summary:"",quotes:[],poem:null,link:""},

  // Horn of Africa
  {country:"South Sudan",region:"horn",reviewed:false,book:"There Is a Country",author:"Various",tags:["independence","civil war","new nation"],summary:"",quotes:[],poem:null,link:""},

  // Central Africa
  {country:"Central African Republic",region:"central",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"Chad",region:"central",reviewed:false,book:"Told by Starlight in Chad",author:"Joseph Brahim Seid",tags:["Sahel","colonialism","French"],summary:"",quotes:[],poem:null,link:""},
  {country:"Gabon",region:"central",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},

  // Southern Africa
  {country:"Botswana",region:"southern",reviewed:false,book:"When Rain Clouds Gather",author:"Bessie Head",tags:[],summary:"",quotes:[],poem:{title:"Love That",author:"Baralong Seboni",clip:"Love that comes\nlike the first rains\non baked earth—\ninstant, necessary—",link:"https://fuuo.blogspot.com/2012/05/african-poets-of-week-compilation.html"},link:""},
  {country:"Eswatini",region:"southern",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"Lesotho",region:"southern",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""},
  {country:"Namibia",region:"southern",reviewed:false,book:"Future read",author:"",tags:[],summary:"",quotes:[],poem:null,link:""}
];

